### ISSUE TITLE
Webhook could not be registered with GitHub.

### ISSUE THREAD

**Issue by isgallagher** [0x4447/0x4447_product_s3_email#22]
# Error Symptoms

Running stage master, getting the following error when trying to deploy the CloudFormation template.

# Error Message

```
Webhook could not be registered with GitHub. Error cause: Not found [StatusCode: 404, Body: {"message":"Not Found","documentation_url":"https://developer.github.com/v3/repos/hooks/#create-a-hook"}] (Service: AWSCodePipeline; Status Code: 400; Error Code: ValidationException;
```

**Comment by isgallagher** [comment]
The GitHub access token I am using only has public read repository access.  Is that the cause of the problem?

**Comment by NickChlam** [comment]
I had this same issue.  I just forked it changed the repo to my own in the cloud formation template.  The error went away.

**Comment by isgallagher** [comment]
@NickChlam sure enough, that did the trick.

I suggest updating the readme to include the repos that need forked, specific permissions required for the GitHub access token, and modifying the CloudFormation template parameters to include the GitHub repo username the repos are forked under (and change the "Owner": "0x4447" to "Owner": !Ref parameter).

**Comment by EdisonJwa** [comment]
I was just got the same problem with the latest master branch even after I forked the repo to my own.

```
Webhook could not be registered with GitHub. Error cause: Not found [StatusCode: 404, Body: {"message":"Not Found","documentation_url":"https://developer.github.com/v3/repos/hooks/#create-a-hook"}] (Service: AWSCodePipeline; Status Code: 400; Error Code: ValidationException; )
```

**Comment by davidgatti** [comment]
What needs to be done is already document - the parameter has a detailed description where and what needs to be done. 

You can read the description here: https://github.com/0x4447/0x4447_product_s3_email/blob/master/03_Parameters/github_token.json

Or read it in the AWS Console.

**Comment by drsromero** [comment]
I got the same error. I created the personal access token as description says
[https://github.com/0x4447/0x4447_product_s3_email/blob/master/03_Parameters/github_token.json](url)
A screenshot with the scopes selected.
[https://subefotos.com/ver/?a9f041aaf39454fb0a5cc31ffc91507ao.png
](url)

Also I forked the repo and changed the owner but the error continue.

`Webhook could not be registered with GitHub. Error cause: Not found [StatusCode: 404, Body: {"message":"Not Found","documentation_url":"https://developer.github.com/v3/repos/hooks/#create-a-hook"}] (Service: AWSCodePipeline; Status Code: 400; Error Code: ValidationException; Request ID: c3af7eac-fa22-491a-bffb-b1dc9883ea78)`

**Comment by davidgatti** [comment]
![Screen Shot 2020-01-20 at 11 57 36 AM](https://user-images.githubusercontent.com/411114/72721324-11de8280-3b7c-11ea-99d4-513838a35dd9.png)

This is how it should look. Dose it look like this?

**Comment by drsromero** [comment]
Yes, the token was generated with the same options selected.
![token](https://subefotos.com/ver/?a9f041aaf39454fb0a5cc31ffc91507ao.png?raw=true)

**Comment by davidgatti** [comment]
This is strange then, since you are the first to have this issue, I wonder what are you doing differently. Hmm... What happens if you check everything?

**Comment by davidgatti** [comment]
And I think Im starting to have an idea of what is going on. I'll do some research and debugging, but if I'm right the webhook will have to be removed.

**Comment by drsromero** [comment]
> This is strange then, since you are the first to have this issue, I wonder what are you doing differently. Hmm... What happens if you check everything?

I did. After that I connected my Github account to Codepipeline in my region through the AWS Console (I suggest updating the readme with this).

I translated this url and forked the repo with my organization instead of my user and tried it.
[https://xbuba.com/questions/56068101](url)

But the error still continue.

**Comment by cplankey** [comment]
I have not forked the repos and used the default setting in the org param when building this and experienced the same error. Can confirm my token permissions match screenshot above.

**Comment by davidgatti** [comment]
Ok, my suspition is that the CodePipeline Webhooks, works in a different way that I thought. Meaning the original repo needs to be updated with a webhook entry for the new deployment, and to do that you need to have the rights to change/edit a repo - and since the repo of the company are not editable by the whole planet, the webhook part of the CF fails to do what needs to be done. 

Below is a edited CF, where I did remove the Parameter for the GitHub APIKey, and removed the Webhooks service from the CodePipelines, please try this CF, and let me know how it goes. 

[CloudFormation.json.zip](https://github.com/0x4447/0x4447_product_s3_email/files/4095862/CloudFormation.json.zip)

**Comment by davidgatti** [comment]
OK, lets try this CF, I did remove the webhooks, this should make the deployment work with no need for forking etc. Let me know how it goes.

[CloudFormation.json.zip](https://github.com/0x4447/0x4447_product_s3_email/files/4095962/CloudFormation.json.zip)

**Comment by cplankey** [comment]
that deployed! thank you!

**Comment by davidgatti** [comment]
OK, then I know the problem now, and I will update the main template within the next few days.

**Comment by aamir7shahab** [comment]
check repository name

**Comment by cdohotaru** [comment]
I was using "git@github.com:MyUsername/MyRepoName.git" instead of "MyUsername/MyRepoName"
Hope this helps! :)
