### ISSUE TITLE
New feature: Rate limiting/Error handling

### ISSUE THREAD

**Issue by zoellner** [0x4447/0x4447_product_s3_email#34]
# My Problem

This is more a question that could turn into a feature request.
I'm wondering how you're handling errors, especially those from send rate limits.
Let's say I can send 100 emails/s with a daily limit of 100k right now and I am sending emails from a couple of services with peaks of 5k emails within a few seconds.

# Solution

Ideally the system would react to the rate limit errors that will come from the ses.sendEmail command and have an exponential delay (or actually keep track of the quota and adjust as needed).

**Comment by davidgatti** [comment]
![giphy](https://user-images.githubusercontent.com/411114/80658093-7798af80-8a85-11ea-930c-57cbbc5ce24d.gif)

This is not the service you are looking for ;) joking aside, this project was not build for a situation like this. For that you'd have to use SQS to queue those emails, and then consume the queue as data is added. Although I don't think you can do this with serverless, You'd need to put your code in to a EC2, and have it run in a loop and have the logic to read multiple emails from SQS so you can send them in batches, and also have the logic to track how many are you sending to then pause when necessary once you are reaching the limit. and resume when you are allowed to.

Doing something like this with Lambda would be hard to do, and would be to complex for no good reason.

My humble opinion from a guy on the other side of the planet :)

**Comment by zoellner** [comment]
Came across this repo in the last few hours https://github.com/PoweredLocal/mailtumble
Their SQS + 1/minute CloudWatch Event seems like a good approach to handle the rate limit

But at that point I might just skip S3 entirely for my use case.

**Comment by davidgatti** [comment]
I'm not sure I follow how they throttle, but if it works for you, that is good. This project was done for personal use, signups emails, news letters that you want to subscribe etc, so there should never be a problem to with limits.

Plus you can send emails, but you should not do that :) this is more for receiving at this moment.
