### ISSUE TITLE
New feature: aws cdk

### ISSUE THREAD

**Issue by Thomazella** [0x4447/0x4447_product_s3_email#37]
# My Problem

The repo would be easier to maintain and to understand if it used code to specify the infra imo

# Solution

- drop some links to the cdk project just in case someone isn't familiar with it
- collect some opinions from maintainers about it, have a conversation

links

[getting started](https://docs.aws.amazon.com/cdk/latest/guide/getting_started.html)
[docs](https://docs.aws.amazon.com/cdk/latest/guide/getting_started.html)
[examples](https://github.com/aws-samples/aws-cdk-examples)

examples are amazing

**Comment by davidgatti** [comment]
U lala @Thomazella sorry to disappoint, but if I could make caffe with a CloudFormation file I would :) CF for life :)
