### ISSUE TITLE
New feature: attachment for sent email

### ISSUE THREAD

**Issue by r33drichards** [0x4447/0x4447_product_s3_email#38]
# My Problem

Ability to send attachments to the `email_out/json` messages
# Solution

the json for an outbound email could be arranged as such

```
{
  "to": "foo@example.com"
  "from": "bar@example.com"
  ...
  "attachments" : [
     "attachment/baz.pdf"
  ]
}
```

and the `baz.pdf` file being located in `email_out/json/attachment/baz.pdf`

this may already be possible but I'm not aware.

**Comment by davidgatti** [comment]
This is something I wanted to do but don't have the bandwidth right now to work on it. And the attachemtns array would be a list of objects with the following content:

```
{
"name": "file_name.pdf"
"data": "base64 content"
}
```

But who knows when I'll have time to work on it.

**Comment by maxrioux100** [comment]
Just leaving a comment to show my interest in this even after 2 years!
