### ISSUE TITLE
Template format error: Unrecognized resource types: [AWS::SES::ReceiptRule, AWS::SES::ReceiptRuleSet]

### ISSUE THREAD

**Issue by YusufHegazy** [0x4447/0x4447_product_s3_email#40]
Been trying to deploy the stack but i keep getting this error whenever I try to submit the template.

**Comment by davidgatti** [comment]
Strange because it is a documented resource: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ses-receiptrule.html,

Can you check that the region you are trying do deploy has access to SES?

**Comment by YusufHegazy** [comment]
> Strange because it is a documented resource: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ses-receiptrule.html,
> 
> Can you check that the region you are trying do deploy has access to SES?

I couldn't find anywhere any information regarding the deploy region of my stack etc...
mind pointing me to the right direction?

**Comment by davidgatti** [comment]
I'm sorry but I can't teach you the basics of AWS over GitHub issues. Check some videos on Youtube, to bump up your knowledge of AWS.

This project is as is, and it requires AWS knowledge to use.
