### ISSUE TITLE
New feature: Deny list

### ISSUE THREAD

**Issue by MHP47** [0x4447/0x4447_product_s3_email#42]
# My Problem

Great project, love having the catch-all option for emails, works perfect.

Thinking about a deny list of some sort, so I can sign up dodgy_website@domain.com and then after using it and not needing it again, add that specific email to a deny list, so when the lambda executes for incoming mail, checks the address against the deny, and drops it instead of formatting into the S3 buckey

# Solution

Seems like a simple DynamoDB table lookup would suffice, but I haven't thought too much into latency lookups, or costs of looking up each time

**Comment by davidgatti** [comment]
Thank you for the suggestion, but the project was designed to not care what you receive, since it is not going to your inbox, it is stored in S3, so if you don't care about the emails, don't go to that folder. 

As you mentioned, it is a catch all.

**Comment by cariaso** [comment]
@MHP47 you may be interested in
https://gist.github.com/dkavraal/356dc60f8f6beb8b5070e891adadab96
