### ISSUE TITLE
Where's the source code?

### ISSUE THREAD

**Issue by stephenh** [0x4447/0x4447_product_s3_email#44]
Hey, your project got linked on reddit or HN, I forget which, and seemed interesting.

I'm poking around, and afaict there are just a bunch of JSON files?

Like the converter logic sounds interesting, but it's just JSON files:

https://github.com/0x4447/0x4447_product_s3_email/tree/master/07_Resources/Repos/converter/Lambda

Disclaimer I haven't cloned the repo and gone through every directory, but dunno, just curious, am I missing something obvious?

**Comment by davidgatti** [comment]
Here you go: https://github.com/topics/0x4447-product-s3-email - please read more carefully the README.md.
